"""
Django settings for StockWeb project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BKO11YHSj7fR0aNHTaJouJ1kdw207rnJlDWaMpngZpo6SoQvt9L5sUuFlhmtqcJZjWqDvxTd4bJhTv1CenHpcdE",
    "VAPID_PRIVATE_KEY":"xBx227kcgdaK2VXCyXLF6k7fUYSz1rnW0wX9tiS0Cgw",
    "VAPID_ADMIN_EMAIL": "kimdjango321@gmail.com"
}


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dt5b!9co1ocjo_uwh3xr6c$j+gv7t7a=c+y$hpm^dh%9^b(1ja'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'webpush',
    'django_celery_beat',
    'stock.apps.StockConfig',
    'crispy_forms',
    'users.apps.UsersConfig',
    'blog.apps.BlogConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'StockWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StockWeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'blog/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'


CRISPY_TEMPLATE_PACK = 'bootstrap4'

# EMAIL_HOST = 'smtp.gmail.com'
# # 메일을 호스트하는 서버
# EMAIL_PORT = '587'
# # gmail과의 통신하는 포트
# EMAIL_HOST_USER = 'kimdjango321@gmail.com'
# # 발신할 이메일
# EMAIL_HOST_PASSWORD = 'django321'
# # 발신할 메일의 비밀번호
# EMAIL_USE_TLS = True
# # TLS 보안 방법
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# # 사이트와 관련한 자동응답을 받을 이메일 주소,'webmaster@localhost'

LOGIN_REDIRECT_URL = 'blog-home'

LOGIN_URL = 'user-login'

CELERY_BROKER_URL = 'redis://localhost:6379'

# CELERY_BEAT_SCHEDULE = {
#     'st': {
#         'task': 'stock.tasks.add',
#         'schedule': 5.0,
#         'args': (10, 10),
#     },
# }

#  celery -A StockWeb.celery beat  세팅에서 설정한 스케줄 실행코드

#  celery -A StockWeb.celery beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler 
# 어드민에서 설정한 스케줄 실행코드

# celery -A StockWeb worker -l info --pool=solo