# Generated by Django 4.0.4 on 2022-05-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockcodes',
            old_name='comapny_code',
            new_name='company_code',
        ),
    ]
