# Generated by Django 4.0.4 on 2022-05-16 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_rename_comapny_code_stockcodes_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcodes',
            name='interested_user',
            field=models.ManyToManyField(related_name='interested_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
