# Generated by Django 4.0.4 on 2022-05-17 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_stockcodes_stockcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=20)),
                ('date', models.TextField()),
                ('link', models.URLField()),
                ('related_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockcode')),
            ],
        ),
    ]
