# Generated by Django 3.2.13 on 2022-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockcode_has_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcode',
            name='crawl_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
